// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKYX5p8Nt1EORlwqYFOMvnStiboVwW7Jg',
    appId: '1:1093064206773:web:f0a3412850ed071b64d1fc',
    messagingSenderId: '1093064206773',
    projectId: 'sunlit-enterprice-train-rfid',
    authDomain: 'sunlit-enterprice-train-rfid.firebaseapp.com',
    storageBucket: 'sunlit-enterprice-train-rfid.appspot.com',
    measurementId: 'G-44902J9VP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABPlrGT9BqvUIRbXHoTF32q5cJQ94dAkA',
    appId: '1:1093064206773:android:428d93705110aee964d1fc',
    messagingSenderId: '1093064206773',
    projectId: 'sunlit-enterprice-train-rfid',
    storageBucket: 'sunlit-enterprice-train-rfid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJYcHY8la8FHBRD1V3R0dzUWoT67Z-m3c',
    appId: '1:1093064206773:ios:f3d201aa92aceb2c64d1fc',
    messagingSenderId: '1093064206773',
    projectId: 'sunlit-enterprice-train-rfid',
    storageBucket: 'sunlit-enterprice-train-rfid.appspot.com',
    androidClientId: '1093064206773-557sgs2sjn5duvdg75mcqksavom87jeg.apps.googleusercontent.com',
    iosClientId: '1093064206773-kv5fbcvrvs0vb00ji6ikg3h9aifcrrjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainrsid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJYcHY8la8FHBRD1V3R0dzUWoT67Z-m3c',
    appId: '1:1093064206773:ios:f3d201aa92aceb2c64d1fc',
    messagingSenderId: '1093064206773',
    projectId: 'sunlit-enterprice-train-rfid',
    storageBucket: 'sunlit-enterprice-train-rfid.appspot.com',
    androidClientId: '1093064206773-557sgs2sjn5duvdg75mcqksavom87jeg.apps.googleusercontent.com',
    iosClientId: '1093064206773-kv5fbcvrvs0vb00ji6ikg3h9aifcrrjl.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainrsid',
  );
}
